"""Initial Equitix schema

Revision ID: f3aac35b130b
Revises: 
Create Date: 2026-09-30 13:56:52.224379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3aac35b130b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stocks',
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=False),
    sa.Column('sector', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('ticker')
    )
    op.create_index(op.f('ix_stocks_ticker'), 'stocks', ['ticker'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('daily_prices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('high', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('low', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('close', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['ticker'], ['stocks.ticker'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ticker_date', 'daily_prices', ['ticker', 'date'], unique=True)
    op.create_table('portfolios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('cash_balance', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('predictions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('predicted_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ticker'], ['stocks.ticker'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pred_ticker_date', 'predictions', ['ticker', 'target_date'], unique=False)
    op.create_table('holdings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('portfolio_id', sa.UUID(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('shares', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('average_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.ForeignKeyConstraint(['ticker'], ['stocks.ticker'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('holdings')
    op.drop_index('idx_pred_ticker_date', table_name='predictions')
    op.drop_table('predictions')
    op.drop_table('portfolios')
    op.drop_index('idx_ticker_date', table_name='daily_prices')
    op.drop_table('daily_prices')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_stocks_ticker'), table_name='stocks')
    op.drop_table('stocks')
    # ### end Alembic commands ###
